### ISSUE TITLE
Implement functions for determining all historical authors of a given line/file

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/blameandshame#4]
We should add a couple of functions for obtaining historical authorship information:

* `authors_of_file` should return the set of authors that have touched a given file, specified by its most recent name. This function should accept two optional arguments: `since` should be used to specify the commit from which the function should collecting authorship information. Similarly, `until` should specify the commit up until (and including) which the function should obtain authorship information.
* `authors_of_line` should return the set of authors that have touched a certain line, specified by its line number in the most recent commit, in a given file. This function should behave in the same manner as `authors_of_file`.

**Comment by ChrisTimperley** [comment]
How should authors be identiifed? By username or by email?

**Comment by jlacomis** [comment]
Closed by pull request #6
