### ISSUE TITLE
get_repo should update the local copy of a repository

### ISSUE THREAD

**Issue by jlacomis** [squaresLab/blameandshame#7]
`get_repo` currently just checks to see if a local copy of a repo exists and uses the local copy without updating it from the remote copy. Any commits made after the repo was first cloned are missed.

**Comment by ChrisTimperley** [comment]
How do we feel about adding a `Project` class that assumes the responsibility for cloning and updating repositories?

**Comment by jlacomis** [comment]
Sounds good to me
