### ISSUE TITLE
Add `last_commit_to_line` method to `util` module

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/blameandshame#8]
Add a function to determine the last commit that touched a given line before a (bug-fixing) commit. If there were no commits to the line before the given commit, `None` should be returned instead.

```
def last_commit_to_line(repo: git.Repo,
                        filename: str,
                        lineno: int,
                        before: git.Commit) -> Optional[git.Commit]
```

It should be possible to implement this function in a single line as a call to `commits_to_line`.

**Comment by jlacomis** [comment]
Closed by #15
